// Generated by https://quicktype.io

export interface MintbaseStoresCollection {
    mb_views_top_stores: MBViewsTopStore[];
}

export interface MBViewsTopStore {
    store_id:   string;
    __typename: Typename;
    total:      number;
    owner:      string;
    name:       string;
}

export enum Typename {
    MBViewsTopStores = "mb_views_top_stores",
}